### ISSUE TITLE
Inferring dates fails for text containing [] and - leading to a ValueError on line 186 of chatparsers.py

### ISSUE THREAD

**Issue by osiloke** [joweich/chat-miner#135]
Sample Whatsapp message

08/04/2022, 16:40 - +234 700 000 0000: ```
[2,4,0,4,11,2602,36] ->   11
[160,3,1719,19,13,-21]  ->  160

```

**Comment by joweich** [comment]
Hey @osiloke, thank you for raising this! 
I drilled down this issue in the regex that identifies if a line is the start of a new message.
Your line 

> [160,3,1719,19,13,-21] -> 160

 [matches our regex pattern](https://www.debuggex.com/r/kZNebKK5aVlvtcA1).
This is clearly a bug that I fixed in #136. Would you mind validating the fix before I merge it and release a new version accordingly? Thank you!! :slightly_smiling_face:
