### ISSUE TITLE
Unrecognized date format

### ISSUE THREAD

**Issue by Landcross** [joweich/chat-miner#24]
Hi! I just did a whatsapp export and put it into chat-miner, but it seems my datetime format is not supported. I was able to get it working by modifying the code a bit, but not in a way that would be good for a PR, hence this issue instead.

My exported format is like this:
`26-04-2022 12:11 - [name]: [message]`

So it's day-month-year hour:minute.
Not only does chat-minder currently not expect a `-` as date separator, it also gets confused later on when it's splitting datetime and message content based on `-` (splitting on ` - ` with spaces around it works better).

**Comment by alfonso46674** [comment]
I ran into the same problem. Maybe WhatsApp exports data differently for each country, or WhatsApp recently updated the date format for exported chats. Either way, I think we would need more people to confirm the issue to take an approach

**Comment by alfonso46674** [comment]
Forgot to add my format, it is [25/09/20 10:27:18 a.m.] [name] : [message]. I think this issue could be caused by the Whatsapp  or phone date configuration

**Comment by joweich** [comment]
@Landcross @alfonso46674 @miguelgazela 
Thank you guys for raising this!
The format of the date in the logs indeed differ depending on different factors. I haven't seen your formats yet, which is why the regex does not properly parse them.
The fix should be quite easy: Simply adjust the regex string _DATEREG_ to incorporate your formats. [This](https://regex101.com/) is a great tool for validating regular expressions.
Feel free to drop a PR to contribute to this project!

**Comment by alfonso46674** [comment]
Sure thing, I'll make sure to integrate my format in the following days!

**Comment by Baesm** [comment]
I would need a little help to contribute as well. My format (WhatsApp, iOS) is like this 

`[DD.MM.YY, hh:mm:ss] name: message`

configuring _DATEREG_ to `r"^\[\d\d\.\d\d\.\d\d, \d\d:\d\d:\d\d\]"` solves the message parsing problem (for now) but results in 

`chat-miner/chatminer/chatparsers.py", line 151, in <listcomp>
    day_and_month = [int(num) for num in line.split(".")[:2]]
ValueError: invalid literal for int() with base 10: '[08'
`

I can not pinpoint the error here, because it seems to crash halfway through ~39k messages. Help is very appreciated!

**Comment by Baesm** [comment]
Following date format (WhatsApp, iOS export) does also not work: 

`[DD.MM.YY, hh:mm:ss] user: message`

configuring _DATEREG_ to 
`r"^\[\d\d\.\d\d\.\d\d, \d\d:\d\d:\d\d\]"` 
only shifts the error to 
`def _parse_message(self, mess):`
 which then fails with
 `File "/usr/local/lib/python3.9/site-packages/dateutil/parser/_parser.py", line 651, in parse
    six.raise_from(ParserError(str(e) + ": %s", timestr), e)
  File "<string>", line 3, in raise_from
dateutil.parser._parser.ParserError: day is out of range for month: [31`

Some major changes to the parsing would be needed, but unfortunately I have no time to do it myself. Just wanted to let you guys know.

**Comment by Landcross** [comment]
> @Landcross @alfonso46674 @miguelgazela Thank you guys for raising this! The format of the date in the logs indeed differ depending on different factors. I haven't seen your formats yet, which is why the regex does not properly parse them. The fix should be quite easy: Simply adjust the regex string _DATEREG_ to incorporate your formats. [This](https://regex101.com/) is a great tool for validating regular expressions. Feel free to drop a PR to contribute to this project!

Like I said in my initial post, simply expanding the regex doesn't work for my format at least, because it gets confused later on when trying to split the message from the datetime (because - is used for both that and in the datetime itself)

**Comment by alfonso46674** [comment]
I've created a [pull request](https://github.com/joweich/chat-miner/pull/30l) to give support to the formats: 
```
[DD/MM/YY hh:mm:ss] user:message
DD/MM/YYYY hh:mm:ss a.m./p.m. - user:message
DD.MM.YYYY hh:mm a.m./p.m. - user:message
```
I've also added more tests to prevent this in the future.

**Comment by Baesm** [comment]
Just replying real quick on mobile without screenshots unfortunately, but the parsing now works and no errors are thrown. 

But I will raise another issue (only partially connected to this one) in the coming days, because the visualisation of the wordcloud now shows the usernames as „most used words“. I will provide screenshots and further documentation over the weekend and maybe try fixing it myself. 

Thanks a lot for maintaining this fun project.
