### ISSUE TITLE
Where did you get chats log data ? 

### ISSUE THREAD

**Issue by slim-python** [joweich/chat-miner#27]

**Comment by alfonso46674** [comment]
I think this should be more of a topic in the discussions tab so that more people with the same question can see the answer.
For whatsapp you can get the chats data as follows: https://faq.whatsapp.com/196737011380816/?cms_platform=android&locale=en_US
For other platform you can google it and usually it will be one of the first results

**Comment by alexdanilowicz** [comment]
There are links in the README for [WhatsApp (via mobile app)](https://faq.whatsapp.com/196737011380816/?cms_id=196737011380816&published_only=true), [Signal (via desktop app)](https://github.com/carderne/signal-export, [Telegram (via desktop app)](https://telegram.org/blog/export-and-more), [Facebook Messenger (via mobile app)](https://www.facebook.com/help/messenger-app/713635396288741?cms_id=713635396288741&published_only=true).

I'll add: if you're looking to analyze iMessage (which it doesn't seem chat-miner supports at this time, but maybe we can partner!), you can check us ([Left on Read](https://github.com/Left-on-Read/leftonread)) out which is a [downloadable Desktop App](https://leftonread.me/) for Mac, no coding experience is required.

**Comment by joweich** [comment]
Indeed, we currently don't support parsing chat logs for iMessage exports.
I opened a respective feature issue #28.
@alexdanilowicz please feel free to open a thread in the discussion section of this GitHub project to discuss a possible collaboration further!
